
-- ==================================================================================================================
-- ===================================   PRIMER PUNTO TRIGGER CON EXCEPTIONS (25%)   ================================
-- ==================================================================================================================

CREATE OR REPLACE FUNCTION CHECK_PASSPORT(PASSPORT NUMBER)
    RETURN BOOLEAN IS
    BEGIN
        FOR query IN (SELECT * FROM karateca WHERE pasaporte = PASSPORT) LOOP
          RETURN FALSE;
        END LOOP;
        RETURN TRUE;
    END;
/
    
CREATE OR REPLACE TRIGGER CONTROL_DATOEV
BEFORE INSERT
  ON evento
  FOR EACH ROW
DECLARE
    cont NUMBER(2) := 0;
BEGIN
    
    FOR peleas IN (SELECT xt.*
                    FROM XMLTABLE('/Evento/Peleas/Pelea'
                            PASSING :NEW.datoev
                            COLUMNS 
                            pas1     NUMBER(20) PATH 'Pas1',
                            pas2     NUMBER(20) PATH 'Pas2',
                            ganador  VARCHAR2(100) PATH 'Ganador',
                            tecnica  VARCHAR2(100) PATH 'Tecnica'
                            ) xt) LOOP

        cont := cont + 1;

        IF cont > 5 THEN 
            raise_application_error(-20005, 'Hay más de 5 peleas.');
        END IF;

        IF peleas.pas1 = peleas.pas2 THEN
            raise_application_error(-20001, 'Hay peleador consigo mismo.');
        END IF;

        IF (peleas.ganador = 0 AND peleas.tecnica IS NOT NULL) THEN
            raise_application_error(-20002, 'Hay empate con técnica');
        END IF;

        IF (peleas.ganador != 0 AND peleas.tecnica IS NULL) THEN
            raise_application_error(-20003, 'Hay ganador sin técnica');
        END IF;

        IF (peleas.ganador != 0 AND peleas.ganador != 1 AND peleas.ganador = 2) THEN
            raise_application_error(-20006, 'El valor del campo ganador solo puede ser 0, 1 o 2.');
        END IF;
        
        IF CHECK_PASSPORT(peleas.pas1) THEN 
            raise_application_error(-20003, 'Pasaporte no encontrado: '||peleas.pas1);
        END IF;

        IF CHECK_PASSPORT(peleas.pas2) THEN 
            raise_application_error(-20003, 'Pasaporte no encontrado: '||peleas.pas2);
        END IF;

    END LOOP;

    IF cont < 1 THEN 
        raise_application_error(-20004, 'Hay menos de una pelea.');
    END IF;

END;
/

-- ==================================================================================================================
-- ===================================================   Punto 2 (75 %)   ===========================================
-- ==================================================================================================================


CREATE TABLE KaratecaPeleador (pasaporte NUMBER PRIMARY KEY NOT NULL,
                            nom VARCHAR2(256) NOT NULL,
                            otronom VARCHAR2(256),
                            nick VARCHAR2(256) NOT NULL,
                            otronick VARCHAR2(256));

CREATE TABLE Pelea (consecutivo INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            pas1 NUMBER NOT NULL,
                            pas2 NUMBER NOT NULL,
                            fecha DATE NOT NULL,
                            ganador NUMBER(1) NOT NULL,
                            tecnica VARCHAR2(256),
                            evento VARCHAR2(256),
                            PRIMARY KEY(consecutivo),
                            FOREIGN KEY(pas1) REFERENCES karatecaPeleador (pasaporte),
                            FOREIGN KEY(pas2) REFERENCES karatecaPeleador (pasaporte));


-- SELECT K.PASAPORTE, P.PASAPORTE FROM KARATECA K FULL JOIN PELEADOR P ON K.PASAPORTE = P.PASAPORTE;

-- (SELECT PASAPORTE FROM KARATECA) UNION
-- (SELECT PASAPORTE FROM PELEADOR WHERE PASAPORTE NOT IN (SELECT PASAPORTE FROM KARATECA)); 


CREATE OR REPLACE PROCEDURE getFromKarateca (pasaport IN NUMBER, nombreout OUT VARCHAR2, nickout OUT VARCHAR2) IS
BEGIN
    FOR person IN (SELECT
        EXTRACTVALUE (datoka, '/Karateca/Nombre') AS nombreKarateca,
        EXTRACTVALUE (datoka, '/Karateca/Nickname') AS nickKarateca
        FROM karateca b WHERE pasaporte = pasaport) LOOP
        nombreout := person.nombreKarateca;
        nickout := person.nickKarateca;
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE getFromPeleador(pasaport IN NUMBER, nombreout OUT VARCHAR2, nickout OUT VARCHAR2) IS
BEGIN
    FOR person IN (SELECT 
        JSON_VALUE(datope, '$.nombre') AS nombrePeleador,
        JSON_VALUE(datope, '$.nickname') AS nickPeleador        
        FROM peleador p WHERE pasaporte = pasaport) LOOP
        nombreout := person.nombrePeleador;
        nickout := person.nickPeleador;
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE FillTableKaratecaPeleador() --HAY QUE CAMBIAR ESOS PARENTESIS VACIOS
IS
    PASSPORT NUMBER;
    NOM VARCHAR2;
    OTRONOM VARCHAR2;
    NICK VARCHAR2;
    OTRONICK VARCHAR2;
BEGIN 
    FOR passports IN (SELECT K.PASAPORTE AS KARATECA,
                             P.PASAPORTE AS PELEADOR 
                        FROM KARATECA K FULL JOIN PELEADOR P ON K.PASAPORTE = P.PASAPORTE) LOOP
        IF (passports.karateca IS NOT NULL AND passports.peleador IS NOT NULL) THEN
            getFromKarateca(passports.karateca, NOM, NICK);
            getFromPeleador(passports.peleador, OTRONOM, OTRONICK);
            PASSPORT := passports.karateca;
        ELSIF (passports.peleador IS NULL) THEN
            getFromKarateca(passports.karateca, NOM, NICK);
            PASSPORT := passports.karateca;
        ELSE
            getFromPeleador(passports.peleador, NOM, NICK);
            PASSPORT := passports.peleador;
        END IF;

        INSERT INTO KaratecaPeleador VALUES (PASSPORT, NOM, OTRONOM, NICK, OTRONICK);

    END LOOP;
END;
/

EXECUTE FillTableKaratecapeleador()

